name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Copy files to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_DNS: ${{ secrets.HOST_DNS }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "$EC2_SSH_KEY" > ec2_key.pem
        chmod 400 ec2_key.pem
        scp -o StrictHostKeyChecking=no -i ec2_key.pem -r . $USERNAME@$HOST_DNS:$TARGET_DIR

    - name: Run deployment script on EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_DNS: ${{ secrets.HOST_DNS }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $USERNAME@$HOST_DNS << 'EOF'
          cd $TARGET_DIR
          source venv/bin/activate
          pip install -r requirements.txt
          alembic upgrade head
          uvicorn app:app --host 0.0.0.0 --port 8000
        EOF