"""add_document_type_table_user_documents

Revision ID: 3fc766fa9253
Revises: a452adfc6bba
Create Date: 2024-06-07 18:16:31.931535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc766fa9253'
down_revision: Union[str, None] = 'a452adfc6bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('document_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_documents', 'document_type')
    # ### end Alembic commands ###
