"""added_is_embedded_to_user_documents

Revision ID: bcbf60b0cf4c
Revises: 3fc766fa9253
Create Date: 2024-06-08 14:55:46.497353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbf60b0cf4c'
down_revision: Union[str, None] = '3fc766fa9253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('is_embedded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_documents', 'is_embedded')
    # ### end Alembic commands ###
